### ISSUE TITLE
Reproducing benchmark results

### ISSUE THREAD

**Issue by CaiSudao** [KevinMusgrave/powerful-benchmarker#34]
![image](https://user-images.githubusercontent.com/37005735/84555229-6a423680-ad4e-11ea-88c0-369baca09154.png)
The picture above is the drive google link. 
I don't know how to reproduce benchmarker result.

**Comment by CaiSudao** [comment]
It seems just the result.

**Comment by KevinMusgrave** [comment]
Download the ```cub_contrastive41_reproduction0``` folder. Then at the command line:
```
python run.py --reproduce_results <path to the folder you downloaded> \
--experiment_name <experiment name>
```

**Comment by CaiSudao** [comment]
Nice. Thanks a lot. I thought the file <cub_contrastive41_reproduction0> is the result of repeated the experiments originally. And it used for obtaining the confidence interval. I was wrong.

**Comment by KevinMusgrave** [comment]
Yeah, actually that folder **is** one of the repeated experiments used to calculate the confidence interval. It contains the config files with the best parameters etc, and when you pass in that folder path to the ```--reproduce_results``` flag, the benchmarker will read those config files.

**Comment by KevinMusgrave** [comment]
Closing for now, please reopen if you have more questions.
