### ISSUE TITLE
 Specify some GPUs in parallel

### ISSUE THREAD

**Issue by CaiSudao** [KevinMusgrave/powerful-benchmarker#41]
Maybe I didn't look at the code in-depth and couldn't understand all coding. I can not find the place to specify some GPUs in parallel.  I can specify in pytorch-metric-learning package.

**Comment by CaiSudao** [comment]
I can specify some GPUs when I learn the pytorch-metric-learning examples.

**Comment by KevinMusgrave** [comment]
Currently this isn't possible, but you can specify multiple GPUs at the command line, before you start the script. 

For example, to use gpus 0, 1, and 3:
```
export CUDA_VISIBLE_DEVICES=0,1,3
```
