### ISSUE TITLE
How to use my own dataset for benchmarking metric learning?

### ISSUE THREAD

**Issue by dorcus01** [KevinMusgrave/powerful-benchmarker#51]
Can you please show me an example of configuring a different dataset from the existing ones in the repo? Thanks!

**Comment by KevinMusgrave** [comment]
Good question. See [this reply](https://github.com/KevinMusgrave/powerful-benchmarker/issues/48#issuecomment-673125087) for steps on how to use your own dataset.

**Comment by dorcus01** [comment]
Thanks a lot!
