### ISSUE TITLE
Is there a way to disable model saving?

### ISSUE THREAD

**Issue by btseytlin** [KevinMusgrave/powerful-benchmarker#57]
Models take a lot of space, but I don't really need them. Is there a way to run benchmarks without saving any models? A way to save the final models (trained with best hyperparamters) only?

**Comment by KevinMusgrave** [comment]
So you'd like to run a bunch of experiments without saving models, and then after they're done, you want to rerun the experiment with the best parameters, but with model saving on.

**Comment by KevinMusgrave** [comment]
Latest version (0.9.33), you can set ```--hook_container~APPLY~2 {save_models: False}```
