### ISSUE TITLE
warning: This overload of nonzero is deprecated

### ISSUE THREAD

**Issue by usuyama** [KevinMusgrave/powerful-benchmarker#60]
Got this warning when running the getting started script

`python run.py --experiment_name test1 --dataset {CUB200: {download: True}} --dataset_root datasets/ --root_experiment_folder experiments`

```
/anaconda/envs/metric_bench/lib/python3.7/site-packages/pytorch_metric_learning/utils/loss_and_miner_utils.py:79: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  a1_idx = matches.nonzero()[:, 0].flatten()
```

**Comment by KevinMusgrave** [comment]
This was fixed in pytorch-metric-learning v0.9.90. I need to make some small changes in this library to make it compatible with v0.9.90. Related: https://github.com/KevinMusgrave/powerful-benchmarker/issues/54
