### ISSUE TITLE
raise KeyError - Triplet Loss

### ISSUE THREAD

**Issue by alpoler** [KevinMusgrave/powerful-benchmarker#61]
I add configuration --experiment_name FGVC_triplet --loss_funcs~OVERRIDE~ {metric_loss: {TripletMarginLoss: {margin: 0.1}}} --check_untrained_accuracy False --num_epochs_train 1 --splits_to_eval [test] and I have encountered with error below

> Traceback (most recent call last):
>   File "/home/aselsan/PycharmProjects/powerful-benchmarker/run.py", line 29, in <module>
>     r.run()
>   File "/home/aselsan/miniconda3/envs/alper/lib/python3.7/site-packages/powerful_benchmarker/runners/single_experiment_runner.py", line 18, in run
>     return self.run_new_experiment_or_resume(self.YR)
>   File "/home/aselsan/miniconda3/envs/alper/lib/python3.7/site-packages/powerful_benchmarker/runners/single_experiment_runner.py", line 33, in run_new_experiment_or_resume
>     return self.start_experiment(args)
>   File "/home/aselsan/miniconda3/envs/alper/lib/python3.7/site-packages/powerful_benchmarker/runners/single_experiment_runner.py", line 22, in start_experiment
>     run_output = api_parser.run()
>   File "/home/aselsan/miniconda3/envs/alper/lib/python3.7/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 17, in run
>     return self.run_train_or_eval()
>   File "/home/aselsan/miniconda3/envs/alper/lib/python3.7/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 40, in run_train_or_eval
>     return self.aggregator.get_accuracy_and_standard_error(hooks, tester, self.meta_record_keeper, self.split_manager.num_split_schemes, "val")
>   File "/home/aselsan/miniconda3/envs/alper/lib/python3.7/site-packages/powerful_benchmarker/aggregators/base_aggregator.py", line 53, in get_accuracy_and_standard_error
>     q, keys = hooks.try_primary_metric(tester, get_average_best_and_sem)
>   File "/home/aselsan/miniconda3/envs/alper/lib/python3.7/site-packages/pytorch_metric_learning/utils/logging_presets.py", line 165, in try_primary_metric
>     return self.try_keys([self.primary_metric], tester, input_func)
>   File "/home/aselsan/miniconda3/envs/alper/lib/python3.7/site-packages/pytorch_metric_learning/utils/logging_presets.py", line 162, in try_keys
>     raise KeyError        
> KeyError
> 
> Process finished with exit code 1

Is it related with current bugs ? I only deal with adding my custom dateset . I don't guess that it causes this problem. I also try with other configuration and whenever i add --splits_to_eval [test], I encounter with same error

**Comment by KevinMusgrave** [comment]
If you don't use the ```--evaluate``` flag, then it assumes that a ```"val"``` split is part of the ```splits_to_eval```. Since you're setting ```splits_to_eval``` to ```"test"``` during training, the accuracy measurements for ```val``` never show up, which is causing the KeyError.

I'll fix this, but in the meantime, were you trying to get the accuracy of your trained model on the test set? If so, first train your model without the ```splits_to_eval``` flag. Then to get test set accuracy, use both the ```--evaluate``` flag and the ```--splits_to_eval [test]``` flag.

**Comment by alpoler** [comment]
Yes , i try to evaluate on test set. I train first with val split and evaluate after it like you mentioned. It works but ı thought that when i add --splits_to_eval [val , test ] , it directly train model with train val splits and evaluate on test set because it worked like this before. Thanks for your help .
