### ISSUE TITLE
How to use Bayesian optimization for non-continuous variables?

### ISSUE THREAD

**Issue by btseytlin** [KevinMusgrave/powerful-benchmarker#64]
I would like to optimize some parameters that have a few discrete possible values. How can I do that?

**Comment by KevinMusgrave** [comment]
The ```~INT_BAYESIAN~``` flag should work

**Comment by btseytlin** [comment]
Thanks! Does it work for string values too?

**Comment by KevinMusgrave** [comment]
No it works based on a range of numbers, like [0,100] will try the integers between 0 and 100. I don't think it's possible to use a set of strings with the underlying optimization library, https://github.com/facebook/Ax

**Comment by KevinMusgrave** [comment]
If you need to use strings somewhere, I guess you'll have to create a mapping from sequential integers to those strings, inside your object. Maybe have the possible strings in a list, and your object takes in the index of the string in that list.
