### ISSUE TITLE
How to select which GPU to use?

### ISSUE THREAD

**Issue by btseytlin** [KevinMusgrave/powerful-benchmarker#66]
I am running some experiments on a server with multiple GPUs, but I only want to use one for benchmarks (colleagues need to work too :) ). Can I do that?

**Comment by KevinMusgrave** [comment]
Have you tried ```export CUDA_VISIBLE_DEVICES``` before you run the python script? For example, this will make only GPUs 0 and 1 visible to the program.
```
export CUDA_VISIBLE_DEVICES=0,1
python run.py ...
```

**Comment by btseytlin** [comment]
Thank you!
