### ISSUE TITLE
Resume, but do reproduction only

### ISSUE THREAD

**Issue by btseytlin** [KevinMusgrave/powerful-benchmarker#71]
I have two experiments where the training died during reproduction. I ended up with the hyperparameters tuned, but no final metric reports. How can I rerun the reproduction?

**Comment by KevinMusgrave** [comment]
Can you be more specific? Are you doing bayesian optimization? What part do you want to reproduce? Just the best hyperparameter experiment, or the whole bayesian optimization process?

**Comment by btseytlin** [comment]
I am doing bayesian optimization. I run an experiment like this:
```
python3 runners/custom_sampler.py --experiment_name custom_sampler \
--dataset~OVERRIDE~ {CUB200: {download: True}} \
--bayes_opt_iters 25 \
--sampler~OVERRIDE~ {CustomSampler: {m: 4, d~BAYESIAN~: [0, 1]}} \
--loss_funcs~OVERRIDE~ \
{metric_loss: {ContrastiveLoss: {\
pos_margin~BAYESIAN~: [0, 1], \
neg_margin~BAYESIAN~: [0, 1]}}} 
```

Then I want to do 10 reproductions with the best parameters. However I don't know a way to do it if the model stops training during the reproductions phase. 

I try to resume it like this:
```
python3 runners/custom_sampler.py --experiment_name custom_sampler --resume_training latest
```
This just exists with no message though and exit code 0.

**Comment by KevinMusgrave** [comment]
Just run the same command as you do for bayesian optimization. (No need to use the resume training flag as it will resume from the latest model by default.)

It will first try to do bayesian optimization, but that is already done so it will skip it. Then it will try to resume training for any existing reproduction experiments, and will exit for any that are already done.
