### ISSUE TITLE
AttributeError: 'BaseAPIParser' object has no attribute 'base_model_output_size'

### ISSUE THREAD

**Issue by seann999** [KevinMusgrave/powerful-benchmarker#8]
This is the error I get when I run `python3 run.py --experiment_name test01 --root_experiment_folder tests --dataset_root ../datasets/`

**Comment by seann999** [comment]
Just had to set `--pytorch_home`

**Comment by seann999** [comment]
Nevermind, it came back
I've setup the datasets and installed the dependencies but can't get it to run it smoothly.

**Comment by KevinMusgrave** [comment]
Can you paste the stack trace?

**Comment by KevinMusgrave** [comment]
Closing for now, please re-open if you still get errors.
