### ISSUE TITLE
Test on benchmark Error

### ISSUE THREAD

**Issue by alpoler** [KevinMusgrave/powerful-benchmarker#84]
return hooks.run_tester_separately(tester, dataset_dict, epoch, trunk_model, embedder_model,classifier_model,
TypeError: run_tester_separately() got multiple values for argument 'splits_to_eval'

When ı try to evaluate trained model on benchmark, I encounter with this type of error. @KevinMusgrave do you know why this type of error occurs ?

Version of powerful benchmarker 0.9.32
Version of pytorch metric learning 0.9.88

**Comment by KevinMusgrave** [comment]
Don't pass in the classifier model. All the accuracy calculation in PML is done using embeddings.
