### ISSUE TITLE
Clarification on precision_at_k computation

### ISSUE THREAD

**Issue by lindsey98** [KevinMusgrave/powerful-benchmarker#86]
Hi Kevin,
   May I clarify how precision_at_k is computed? Is it like this: given a test (or validation) data point, it finds the nearest neighbour within test (or validation) set, and check its label consistency? I have this confusion because another way of evaluation is: given a test (or validation) data point, it finds the nearest neighbour in training (or some other reference) set. But since your train/va/test split could be class disjoint, so I guess you use the former one?

**Comment by KevinMusgrave** [comment]
Yes it uses the former method (val data point --> find nearest neighbors in val set)

**Comment by lindsey98** [comment]
Ok, thanks!
