### ISSUE TITLE
Reproducing benchmark results only gives validation accuracy

### ISSUE THREAD

**Issue by cerebrai** [KevinMusgrave/powerful-benchmarker#88]
Hi,

I tried to reproduce results using the method described in issue #34; however, the ouput gives me validation accuracies only and accuracy on test set are not reproted. The only file available in meta_logs/saved_csvs after the experiment finished is 
"MeanAggregator_accuracies_normalized_compared_to_self_GlobalEmbeddingSpaceTester_level_0_VAL.csv"

**Comment by KevinMusgrave** [comment]
Hmm can you try this?

```
python run.py --experiment_name your_experiment_name \
--evaluate --splits_to_eval [test]

# or this command for concatenated embeddings
python run.py --experiment_name your_experiment_name \
--evaluate_ensemble --splits_to_eval [test]

```

**Comment by cerebrai** [comment]
Thanks a lot ... It solves the issue
